export const bniRegions = [
  { label: "Medan", value: 1 },
  { label: "Padang", value: 2 },
  { label: "Palembang", value: 3 },
  { label: "Bandung", value: 4 },
  { label: "Semarang", value: 5 },
  { label: "Surabaya", value: 6 },
  { label: "Makassar", value: 7 },
  { label: "Denpasar (Bali–NTB–NTT)", value: 8 },
  { label: "Banjarmasin", value: 9 },
  { label: "Jakarta Senayan", value: 10 },
  { label: "Manado", value: 11 },
  { label: "Jakarta Kota", value: 12 },
  { label: "Jakarta BSD (Tangerang)", value: 14 },
  { label: "Jakarta Kemayoran", value: 15 },
  { label: "Tanah Papua (Jayapura)", value: 16 },
  { label: "Yogyakarta", value: 17 },
  { label: "Malang", value: 18 },
];
