// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ConfigProvider } from "antd";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen relative">
          <Navbar />

          <main className="flex-grow bg-light-tosca">
            <div className="flex flex-col items-center justify-center max-w-[1200px] mx-8 lg:mx-auto py-12">
              <ConfigProvider
                theme={{
                  token: {
                    colorPrimary: "#30a5a2",
                  },
                }}
              >
                {children}
              </ConfigProvider>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
