// app/layout.tsx
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/queryClient";
import ProgressProvider from "@/providers/progressProvider";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Griyata by BNI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakarta.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: "var(--font-jakarta), sans-serif" }}
      >
        <QueryProvider>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#30a5a2",
                fontFamily: "var(--font-jakarta), sans-serif",
              },
            }}
          >
            <AntdRegistry>
              <ProgressProvider>{children}</ProgressProvider>
            </AntdRegistry>
          </ConfigProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
